export const defaultUser = {
    HOSTPLANT: '',
    USERNAME: '',
    USERLOCALE: '',
    CUSTOMERNAME: '',
    USERFULLNAME: '',
    USERTITLE: '',
    USEREMAIL: '',
    USERPHONE_1: '',
    USERPHONE_MOBILE: '',
    INTERNALROLES: '',
    DEPARTMENT: '',
    COMPANY_ID: 0,
    HOOK_URL: '',
    DATECREATED: '2021-08-31T00:00:00',
    AVATAR: '/webservices/metronic9/media/avatars/blank.png',
}

export const sampleTableData = [
    {
        firstName: 'Stephen',
        lastName: 'Smith',
        age: 42,
        visits: 100,
        status: 'online',
        progress: 50,
    },
    {
        firstName: 'John',
        lastName: 'Doe',
        age: 44,
        visits: 40,
        status: 'vacation',
        progress: 80,
    },
    {
        firstName: 'Jane',
        lastName: 'Doe',
        age: 35,
        visits: 20,
        status: 'online',
        progress: 10,
    },
    {
        firstName: 'Betty',
        lastName: 'Rogers',
        age: 41,
        visits: 80,
        status: 'online',
        progress: 70,
    },
    {
        firstName: 'Derek',
        lastName: 'Flint',
        age: 52,
        visits: 10,
        status: 'away',
        progress: 30,
    },
    {
        firstName: 'Arnold',
        lastName: 'Roark',
        age: 42,
        visits: 50,
        status: 'online',
        progress: 60,
    },
    {
        firstName: 'Dino',
        lastName: 'Murray',
        age: 81,
        visits: 10,
        status: 'offline',
        progress: 100,
    },
]