export const defaultUser = {
    HOSTPLANT: '',
    USERNAME: '',
    USERLOCALE: '',
    CUSTOMERNAME: '',
    USERFULLNAME: '',
    USERTITLE: '',
    USEREMAIL: '',
    USERPHONE_1: '',
    USERPHONE_MOBILE: '',
    INTERNALROLES: '',
    DEPARTMENT: '',
    COMPANY_ID: 0,
    HOOK_URL: '',
    DATECREATED: '2021-08-31T00:00:00',
    AVATAR: '/webservices/metronic9/media/avatars/blank.png',
}

export const sampleTableData = [
    {
        firstName: 'Barney',
        lastName: 'Rubble',
        age: 42,
        visits: 100,
        status: 'online',
        progress: 50,
    },
    {
        firstName: 'Fred',
        lastName: 'Flintstone',
        age: 44,
        visits: 40,
        status: 'vacation',
        progress: 80,
    },
    {
        firstName: 'Bam Bam',
        lastName: 'Rubble',
        age: 5,
        visits: 20,
        status: 'online',
        progress: 10,
    },
    {
        firstName: 'Wilma',
        lastName: 'Flintstone',
        age: 41,
        visits: 80,
        status: 'online',
        progress: 70,
    },
    {
        firstName: 'Pebbles',
        lastName: 'Flintstone',
        age: 2,
        visits: 10,
        status: 'away',
        progress: 30,
    },
    {
        firstName: 'Betty',
        lastName: 'Rubble',
        age: 42,
        visits: 50,
        status: 'online',
        progress: 60,
    },
    {
        firstName: 'Dino',
        lastName: 'Dinosaur',
        age: 1000000,
        visits: 10,
        status: 'offline',
        progress: 100,
    },
]